name: Screener
on: [push, workflow_dispatch]
jobs:
  run:
      runs-on: ubuntu-latest
          steps:
                - uses: actions/checkout@v4
                      - run: python main.py
                              env:
                                        LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
                                        
